apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generation: 1
  namespace: production
  labels:
    app: medic-deliverybot
    track: stable
  name: medic-deliverybot
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: medic-deliverybot
      track: stable
  template:
    metadata:
      labels:
        app: medic-deliverybot
        track: stable
    spec:
      nodeSelector:
        availability.zone: eu-west-2a
        k8s.environment: production6a
      containers:
      - image: medicmobile/deliverybot:latest
        imagePullPolicy: Always
        name: deliverybot
        env:
        - name: APP_ID
          value: "put_your_value"
        - name: CLIENT_ID
          value: "put_your_value"
        - name: BASE_URL
          value: "https://deliverybot.app.medicmobile.org"
        - name: CLIENT_SECRET
          value: put_your_value
        - name: WEBHOOK_SECRET
          value: put_your_value
        - name: PRIVATE_KEY
          value: ""
        - name: WEBHOOK_PROXY_URL
          value: " Go to https://smee.io/new set this to the URL that you are redirected to"

        resources:
          limits:
            memory: 2Gi
            cpu: 2
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
