apiVersion: v1
kind: Service
metadata:
  name: medic-deliverybot-service
  namespace: production
spec:
  selector:
    app: medic-deliverybot
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30932
  type: NodePort
